image: maven:3.8.4-openjdk-11-slim

variables:
 MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  timeout: 30 minutes
  script:
    - mvn clean verify -B
